version: "3.7"

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - ARDB_SERVICE_HOST=ardb

  ardb:
    image: lupino/ardb-server
    env_file:
      - ~/.dinner-at-home.env
    ports:
      - "16379:16379"
    volumes:
      - ./conf/ardb.conf:/etc/ardb.conf:ro
      - ./data:/data
      - ./backup:/backup