version: "3.7"

services:
  app:
    build: .
    env_file:
      - ~/homemenu.env
  ardb:
    image: lupino/ardb-server
    ports:
      - "16379:16379"
    volumes:
      - ./conf/ardb.conf:/etc/ardb.conf:ro
      - /data:/data
      - /backup:/backup